[versions]
androidGradlePlugin = "7.2.2"
kotlin = "1.7.0"
coroutines = "1.6.4"
lifecycle = "2.5.1"
compose = "1.2.0"
hilt = "2.42"
hiltExt = "1.0.0"
okhttp = "4.10.0"
arouter = "1.5.2"
room = "2.4.3"
androidxCompose = "1.2.0"

[libraries]
appcompat = "androidx.appcompat:appcompat:1.4.2"
material3 = "com.google.android.material:material:1.6.1"
androidx-core-ktx = "androidx.core:core-ktx:1.8.0"
androidx-work = "androidx.work:work-runtime-ktx:2.8.0-alpha01"
activity-ktx = "androidx.activity:activity-ktx:1.5.1"
fragment-ktx = "androidx.fragment:fragment-ktx:1.5.1"
collection-ktx = "androidx.collection:collection-ktx:1.2.0"
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3"
gson = "com.google.code.gson:gson:2.9.1"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"

activity-compose = "androidx.activity:activity-compose:1.5.1"
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit2 = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit2-kotlinx-serialization-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"

arouter = { module = "com.alibaba:arouter-api", version.ref = "arouter" }
arouter-compiler = { module = "com.alibaba:arouter-compiler", version.ref = "arouter" }

log-timber = "com.jakewharton.timber:timber:5.0.1"
utils = "com.blankj:utilcodex:1.31.0"

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
commonLibs = ["appcompat", "material3", "androidx-core-ktx", "activity-ktx", "androidx-work", "fragment-ktx", "collection-ktx", "lifecycle-runtime-ktx", "lifecycle-livedata-ktx", "lifecycle-viewmodel-ktx", "kotlinx-coroutines-android", "kotlinx-serialization-json", "gson"]
composeLibs = ["activity-compose", "lifecycle-viewmodel-compose", "compose-material", "compose-animation", "compose-ui-tooling"]
hiltLibs = ["hilt-android", "hilt-gradlePlugin", "hilt-ext-compiler", "hilt-ext-work"]
roomLibs = ["room-runtime", "room-ktx", "room-paging"]
httpLibs = ["okhttp", "okhttp-logging-interceptor", "retrofit2", "retrofit2-kotlinx-serialization-converter"]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }



